### ISSUE TITLE
I cannot Submit  and make Article work both in Marketing and Blog example.

### ISSUE THREAD

**Issue by itamair** [arshad/next-drupal#1]
Great project, with great instructions and documentation.
Everything works as expected in my first installation and attempt,
but the Article content types, that cannot be submitted both in the Marketing and Blog examples.
It returns "404 | This page could not be found." ... 
May be I missed some crucial settings? (but I successfully completed all the Readme.md steps ... )

<img width="1773" alt="Screenshot 2021-02-12 at 00 24 04" src="https://user-images.githubusercontent.com/1429859/107711872-ab695c80-6cc8-11eb-8101-62d961c690a3.png">

**Comment by arshad** [comment]
Can you check if the Article entity type is using the entity reference field resolver? See `/admin/config/services/next/entity-types/node.article/edit`

**Comment by itamair** [comment]
After default installing all I found this settings (and it wasn't working as described above):
<img width="1403" alt="Screenshot 2021-02-12 at 09 27 41" src="https://user-images.githubusercontent.com/1429859/107745454-a03c1e00-6d14-11eb-92ba-02f770a94c66.png">

**Comment by itamair** [comment]
Then I changed to this: 
<img width="1403" alt="Screenshot 2021-02-12 at 09 27 41" src="https://user-images.githubusercontent.com/1429859/107745577-cfeb2600-6d14-11eb-8bf4-03898618c99c.png">

and now everything is breaking even worse, when I try to submit an article, also one of the existing:

<img width="1321" alt="Screenshot 2021-02-12 at 09 30 12" src="https://user-images.githubusercontent.com/1429859/107745740-0c1e8680-6d15-11eb-9c3a-42052bcf24a9.png">

<img width="1395" alt="Screenshot 2021-02-12 at 09 30 17" src="https://user-images.githubusercontent.com/1429859/107745756-10e33a80-6d15-11eb-9bef-daca8b60a72b.png">

**Comment by arshad** [comment]
It looks like the seed db in the repo is not up to date. I'll fix this. Can you try editing the node (from /admin/content), select a site and see if it works. Thank you.

**Comment by arshad** [comment]
Looks like `DRUPAL_SITE_ID` was missing from the `.env.example` files. I fixed it. Should be ok now. Can you `git pull` and re-run the following commands again?

```
cp examples/example-blog/.env.example examples/example-blog/.env.local
cp examples/example-marketing/.env.example examples/example-marketing/.env.local
```

Then `yarn dev` and visit http://localhost:8080/blog/business-painting-operation-pick-support-land-time-manager

**Comment by itamair** [comment]
Amaziiin! Looks working fine. Thanks a lot!!!
Just last question. I can see that the "Measure pattern produce difficult guess base" is being correctly published in the "Example Marketing" next.js frontend site. But how is it possible to get the internal next.js route of it ... (and directly access it)?

**Comment by itamair** [comment]
fee free to close this with your last comment ...

**Comment by itamair** [comment]
Last note. It seems that versioned files in this folder: examples/drupal-site/database changes some way after `yarn dev` ...

**Comment by arshad** [comment]
> But how is it possible to get the internal next.js route of it ... (and directly access it)?

In the **dev** version of the module, we added links to view the status of the content and a direct link to view it on the site (if it is published).

<img width="1719" alt="Measure_pattern_produce_difficult_guess_base___Next_js___Drupal" src="https://user-images.githubusercontent.com/124599/107765365-22dfd000-6d4b-11eb-8aa3-f4a3ae11948c.png">

You can test this:

1. Copy `modules/next` into `examples/drupal-site/web/modules/contrib/next`.
2. Clear the Drupal cache.

You should see the toolbar.

**Comment by itamair** [comment]
Nice!!! (super nice ... )
Last note. what about those versioned files in this folder: examples/drupal-site/database that change some way after yarn dev ... ? Am I right?

**Comment by arshad** [comment]
Ah, the only reason the database is versioned is to make it easier to run the demo. You start with a pre-installed Drupal with content type and fields configured. It's showing as changed when you run the demo because it's updated when you logged in (user last timestamp, and cache values..etc).

In a real world application, your database would be hosted and not versioned :)

I'll go ahead and mark this issue as closed. Feel free to open a new thread if you have any question.

Appreciate the feedback (we made the demo better for everyone else).

Thank you

**Comment by itamair** [comment]
Sure. Super Great Job Arshad! I will go deeper into this ... and open new issues eventually.
