### ISSUE TITLE
Vercel shows internal server error for next-drupal node module

### ISSUE THREAD

**Issue by sybercoda** [arshad/next-drupal#3]
14:00:51.677 | Error: Internal Server Error
-- | --
14:00:51.677 | at /vercel/path0/node_modules/next-drupal/dist/index.js:86:19
14:00:51.677 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
14:00:51.677 | at async getStaticPaths (/vercel/path0/.next/server/pages/blog/[...slug].js:3196:17)
14:00:51.678 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:16:80)
14:00:51.678 | at async /vercel/path0/node_modules/next/dist/build/utils.js:26:622
14:00:51.678 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)

**Comment by arshad** [comment]
Can you give me a bit more info? I'll take a look at `next-drupal/dist/index.js:86:19` but more context would be helpful. Thanks.

**Comment by sybercoda** [comment]
@arshad The error is appearing in Vercel build log, as provided below. Please let me know if you anything here indicative of something I did wrong on my side. 

13:59:34.834  	Cloning gitlab.com/quest-king/test-site (Branch: master, Commit: 2964140)
13:59:44.293  	Cloning completed: 9.460s
13:59:45.220  	Analyzing source code...
13:59:46.704  	Installing build runtime...
13:59:48.744  	Build runtime installed: 2.040s
13:59:51.548  	Looking up build cache...
13:59:51.670  	Build cache found. Downloading...
13:59:53.092  	Build cache downloaded [25.36 MB]: 1421.673ms
13:59:54.418  	WARNING: You should not upload the `.next` directory.
13:59:54.420  	Installing dependencies...
13:59:55.529  	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
13:59:56.553  	npm WARN @theme-ui/theme-provider@0.6.2 requires a peer of @theme-ui/css@0.6.0 but none is installed. You must install peer dependencies yourself.
13:59:56.561  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
13:59:56.562  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
13:59:56.562  	up to date in 1.693s
13:59:56.679  	51 packages are looking for funding
13:59:56.679  	  run `npm fund` for details
13:59:56.691  	Detected Next.js version: 10.2.0
13:59:56.693  	Running "npm run build"
13:59:56.903  	> basic-site@0.1.0 build /vercel/path0
13:59:56.903  	> next build
13:59:57.246  	info  - Loaded env from /vercel/path0/.env.production
13:59:57.525  	info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
13:59:57.639  	info  - Checking validity of types...
14:00:00.969  	info  - Creating an optimized production build...
14:00:04.257  	info  - Compiled successfully
14:00:04.257  	info  - Collecting page data...
**14:00:05.182  	Error: Internal Server Error
14:00:05.182  	    at /vercel/path0/node_modules/next-drupal/dist/index.js:86:19
14:00:05.182  	    at processTicksAndRejections (internal/process/task_queues.js:93:5)
14:00:05.182  	    at async getStaticPaths (/vercel/path0/.next/server/pages/[...slug].js:2669:17)
14:00:05.182  	    at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:16:80)
14:00:05.182  	    at async /vercel/path0/node_modules/next/dist/build/utils.js:26:622
14:00:05.182  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)
14:00:05.184  	Error: Internal Server Error
14:00:05.184  	    at /vercel/path0/node_modules/next-drupal/dist/index.js:86:19
14:00:05.184  	    at processTicksAndRejections (internal/process/task_queues.js:93:5)
14:00:05.184  	    at async getStaticPaths (/vercel/path0/.next/server/pages/blog/[...slug].js:3196:17)
14:00:05.184  	    at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:16:80)
14:00:05.184  	    at async /vercel/path0/node_modules/next/dist/build/utils.js:26:622
14:00:05.184  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)**
14:00:05.197  	info  - Generating static pages (0/5)
14:00:05.499  	info  - Generating static pages (1/5)
14:00:05.505  	info  - Generating static pages (2/5)
14:00:05.506  	info  - Generating static pages (3/5)
**14:00:05.928  	Error: Internal Server Error
14:00:05.928  	    at /vercel/path0/node_modules/next-drupal/dist/index.js:86:19
14:00:05.928  	    at processTicksAndRejections (internal/process/task_queues.js:93:5)
14:00:05.928  	    at async getStaticProps (/vercel/path0/.next/server/pages/index.js:3236:20)
14:00:05.928  	    at async renderToHTML (/vercel/path0/node_modules/next/dist/next-server/server/render.js:28:1689)
14:00:05.928  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:26:6
14:00:05.928  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)**
14:00:05.964  	info  - Generating static pages (5/5)
14:00:05.965  	info  - Finalizing page optimization...
14:00:05.989  	Page                             Size     First Load JS
14:00:05.989  	┌ ● / (ISR: 1 Seconds)           1.15 kB        95.7 kB
14:00:05.989  	├   /_app                        0 B            84.5 kB
14:00:05.989  	├ ● /[...slug]                   1.67 kB        92.2 kB
14:00:05.989  	├ ○ /404                         3.03 kB        87.5 kB
14:00:05.989  	├ λ /api/exit-preview            0 B            84.5 kB
14:00:05.989  	├ λ /api/preview                 0 B            84.5 kB
14:00:05.990  	└ ● /blog/[...slug]              905 B          95.4 kB
14:00:05.990  	+ First Load JS shared by all    84.5 kB
14:00:05.990  	  ├ chunks/2.47f79c.js           17.7 kB
14:00:05.990  	  ├ chunks/commons.cd9bd9.js     13.4 kB
14:00:05.990  	  ├ chunks/framework.0529c1.js   42 kB
14:00:05.990  	  ├ chunks/main.e3016c.js        6.87 kB
14:00:05.990  	  ├ chunks/pages/_app.047fc0.js  3.47 kB
14:00:05.990  	  └ chunks/webpack.ce1b5f.js     993 B
14:00:05.990  	λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
14:00:05.990  	○  (Static)  automatically rendered as static HTML (uses no initial props)
14:00:05.990  	●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
14:00:05.990  	   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
14:00:08.547  	Traced Next.js server files in: 2.459s
14:00:09.319  	WARNING: Unable to find source file for page next/dist/pages/_error.js
14:00:09.425  	Created all serverless functions in: 877.983ms
14:00:09.834  	Uploading build outputs...
14:00:10.625  	Deploying build outputs...
14:00:15.910  	Build completed. Populating build cache...
14:00:21.095  	Uploading build cache [25.36 MB]...
14:00:21.585  	Build cache uploaded: 490.13ms
14:00:22.101  	Done with "package.json"

**Comment by sybercoda** [comment]
Closing this issue out as I believe issue was due to pushing .next directory to vercel
